import {
  AlignmentType, BorderStyle, Document, HeadingLevel,
  ImageRun, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType,
} from 'docx';
import ExcelJS from 'exceljs';
import type { AnalysisRow } from '@/lib/calculations/external-stability';
import type { InternalStabilityRow } from '@/lib/calculations/internal-stability';
import type { PanelFaceResult } from '@/lib/calculations/panel-face';

const N = (v: number, d = 4) => (isFinite(v) && !isNaN(v) ? v.toFixed(d) : '—');

// ─── Shared types ──────────────────────────────────────────────────────────────

export interface AbutmentCombinedData {
  projectName: string; projectLocation: string;
  designTypeName: string; createdBy: string; generatedAt: Date;
  extParams: Record<string, string>;
  intParams: Record<string, string>;
  extRows: AnalysisRow[];
  intRows: InternalStabilityRow[];
}

export interface WingCombinedData {
  projectName: string; projectLocation: string;
  designTypeName: string; createdBy: string; generatedAt: Date;
  extParams: Record<string, string>;
  intParams: Record<string, string>;
  extLlRows: AnalysisRow[];
  extNoLlRows: AnalysisRow[];
  intRows: InternalStabilityRow[];
}

export interface PanelFaceReportData {
  projectName: string; projectLocation: string;
  designTypeName: string; createdBy: string; generatedAt: Date;
  params: Record<string, string>;
  result: PanelFaceResult;
  inputs: { barNumHor: number; spacingHor: number; barNumVert: number; spacingVert: number; huStr: number; huEe: number };
}

// ─── Excel helpers ─────────────────────────────────────────────────────────────

const ADEQUATE_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1FAE5' } };
const INADEQUATE_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };

function addSheet(wb: ExcelJS.Workbook, name: string, headers: string[], data: (string | number)[][]) {
  const ws = wb.addWorksheet(name);
  ws.addRow(headers).eachCell((c) => {
    c.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
    c.alignment = { horizontal: 'center', wrapText: true };
    c.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
  });
  for (const row of data) {
    const r = ws.addRow(row);
    r.eachCell((c) => {
      c.alignment = { horizontal: 'center' };
      c.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      if (typeof c.value === 'string') {
        if (c.value === 'Adequate') c.fill = ADEQUATE_FILL;
        else if (c.value === 'Inadequate') { c.fill = INADEQUATE_FILL; c.font = { color: { argb: 'FF991B1B' } }; }
      }
    });
  }
  ws.columns.forEach((col) => { col.width = Math.max(12, (col.header?.toString().length ?? 12) + 4); });
}

function addInfoSheet(wb: ExcelJS.Workbook, name: string, {
  projectName, projectLocation, designTypeName, createdBy, generatedAt,
}: { projectName: string; projectLocation: string; designTypeName: string; createdBy: string; generatedAt: Date },
params: Record<string, string>) {
  const info = wb.addWorksheet(name);
  info.addRow(['MSE Design Analysis Report']).getCell(1).font = { bold: true, size: 14 };
  info.addRow(['Project', projectName]);
  info.addRow(['Location', projectLocation]);
  info.addRow(['Design Type', designTypeName]);
  info.addRow(['Generated By', createdBy]);
  info.addRow(['Date', generatedAt.toLocaleDateString()]);
  info.addRow([]);
  info.addRow(['Parameter', 'Value']).getCell(1).font = { bold: true };
  for (const [k, v] of Object.entries(params)) info.addRow([k, v]);
  info.columns = [{ width: 28 }, { width: 30 }];
}

function addExternalSheets(wb: ExcelJS.Workbook, prefix: string, rows: AnalysisRow[]) {
  addSheet(wb, `${prefix}Loads`,
    ['DH (ft)', 'RL (ft)', 'h_eq', 'P_LS.V', 'P_EV', 'M_LS.V', 'M_EV', 'P_LS.H', 'P_EH', 'P_EQ', 'M_LS.H', 'M_EH', 'M_EQ'],
    rows.map((r) => [r.dh, r.rl, r.hEq, r.pLsV, r.pEv, r.mLsV, r.mEv, r.pLsH, r.pEh, r.pEq, r.mLsH, r.mEh, r.mEq]),
  );
  addSheet(wb, `${prefix}Load Combs`,
    ['DH', 'Pu Ser-I V', 'Mu Ser-I V', 'Pu Str-I V', 'Mu Str-I V', 'Pu EE-I V', 'Mu EE-I V', 'Pu Ser-I L', 'Mu Ser-I L', 'Pu Str-I L', 'Mu Str-I L', 'Pu EE-I L', 'Mu EE-I L'],
    rows.map((r) => [r.dh, r.puSerIV, r.muSerIV, r.puStrIV, r.muStrIV, r.puEeIV, r.muEeIV, r.puSerILat, r.muSerILat, r.puStrILat, r.muStrILat, r.puEeILat, r.muEeILat]),
  );
  addSheet(wb, `${prefix}Str I`,
    ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
    rows.map((r) => [r.dh, r.eccBrgStrI, r.suBrgStrI, r.checkBrgStrI, r.eccOvtStrI, r.checkOvtStrI, r.phiRrStrIClass1, r.phiRrStrIFSoil, r.checkSldStrIClass1, r.checkSldStrIFSoil]),
  );
  addSheet(wb, `${prefix}EE I`,
    ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
    rows.map((r) => [r.dh, r.eccBrgEeI, r.suBrgEeI, r.checkBrgEeI, r.eccOvtEeI, r.checkOvtEeI, r.phiRrEeIClass1, r.phiRrEeIFSoil, r.checkSldEeIClass1, r.checkSldEeIFSoil]),
  );
  addSheet(wb, `${prefix}Ser I`,
    ['DH', 'ecc Brg', 'Su Brg', 'Brg'],
    rows.map((r) => [r.dh, r.eccBrgSerI, r.suBrgSerI, r.checkBrgSerI]),
  );
  addSheet(wb, `${prefix}% Demand`,
    ['DH', 'Brg Str-I', 'Brg EE-I', 'Brg Ser-I', 'Ovt Str-I', 'Ovt EE-I', 'Sld Str-I', 'Sld EE-I', 'Ctrl %', 'Controls'],
    rows.map((r) => [r.dh, r.demBrgStrI, r.demBrgEeI, r.demBrgSerI, r.demOvtStrI, r.demOvtEeI, r.demSldStrI, r.demSldEeI, r.demCtrl, r.limitState]),
  );
  addSheet(wb, `${prefix}Summary`,
    ['DH (ft)', 'RL (ft)', 'NL', 'Ctrl % Demand', 'Controlling Limit State'],
    rows.map((r) => [r.dh, r.rl, r.nl, r.demCtrl, r.limitState]),
  );
}

async function addInternalSheets(wb: ExcelJS.Workbook, prefix: string, rows: InternalStabilityRow[]) {
  addSheet(wb, `${prefix}Stress-Load`,
    ['DH (ft)', 'RL (ft)', 'z (ft)', 'σEV.Z', 'h_eq', 'σLS.Z', 'ωIR', 'ωAE', 'ωEQ.1', 'ωEQ.2', 'PEQ', 'σEQ'],
    rows.map((r) => [r.dh, r.rl, r.z, r.sEvZ, r.hEq, r.sLsZ, r.wIr, r.wAe, r.wEq1, r.wEq2, r.pEq, r.sEq]),
  );
  addSheet(wb, `${prefix}Geostrip`,
    ['z (ft)', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
    rows.map((r) => [r.z, r.sVStrI, r.sHStrI, r.sVEeI, r.sHEeI, r.tMaxStrIGstrip, r.tMaxEeIGstrip, r.lEStrIGs, r.lEEeIGs, r.lEGeostrip, r.lAGs, r.rlMinGeostrip, r.ltdsGeostrip, r.poGeostripCheck]),
  );
  addSheet(wb, `${prefix}Geogrid`,
    ['z (ft)', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
    rows.map((r) => [r.z, r.sVStrI, r.sHStrI, r.sVEeI, r.sHEeI, r.tMaxStrIGgrid, r.tMaxEeIGgrid, r.lEStrIGg, r.lEEeIGg, r.lEGeogrid, r.lAGg, r.rlMinGeogrid, r.ltdsGeogrid, r.poGeogridCheck]),
  );
  addSheet(wb, `${prefix}Met Grid`,
    ['z (ft)', "F'", 'kR.Sg', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
    rows.map((r) => [r.z, r.fpMg, r.krSg, r.sVStrIMg, r.sHStrIMg, r.sVEeIMg, r.sHEeIMg, r.tMaxStrISg, r.tMaxEeISg, r.lEStrIMg, r.lEEeIMg, r.lESg, r.lASg, r.rlMinSg, r.ltdsSg, r.poSgCheck]),
  );
  addSheet(wb, `${prefix}Rib Strip`,
    ['z (ft)', "F'", 'kR.Ss', 'Rc.Ss', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
    rows.map((r) => [r.z, r.fpSs, r.krSs, r.rcSs, r.sVStrISs, r.sHStrISs, r.sVEeISs, r.sHEeISs, r.tMaxStrISs, r.tMaxEeISs, r.lEStrISs, r.lEEeISs, r.lESs, r.lASs, r.rlMinSs, r.ltdsSs, r.poSsCheck]),
  );
  addSheet(wb, `${prefix}LTDS`,
    ['z (ft)', 'Geostrip Str-I', 'Geogrid Str-I', 'Met Grid Str-I', 'Rib Strip Str-I', 'Geostrip EE-I', 'Geogrid EE-I', 'Met Grid EE-I', 'Rib Strip EE-I'],
    rows.map((r) => [r.z, r.ltdsGeostrip, r.ltdsGeogrid, r.ltdsSg, r.ltdsSs, r.ltdsEeIGs, r.ltdsEeIGg, r.ltdsEeISg, r.ltdsEeISs]),
  );

  const chartPng = await renderLtdsChart(rows);
  if (chartPng) {
    const chartWs = wb.addWorksheet(`${prefix}Chart`);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const imageId = wb.addImage({ buffer: chartPng as any, extension: 'png' });
    chartWs.addImage(imageId, { tl: { col: 0, row: 0 }, ext: { width: 900, height: 600 } });
  }
}

async function renderLtdsChart(rows: InternalStabilityRow[]): Promise<Buffer | null> {
  try {
    const zValues = rows.map((r) => r.z);
    const maxZ = Math.max(...zValues);
    const make = (ltds: number[]) => ltds.map((v, i) => ({ x: v / 1000, y: zValues[i] }));
    const chartConfig = {
      type: 'scatter',
      data: {
        datasets: [
          { label: 'Geostrip',       data: make(rows.map((r) => r.ltdsGeostrip)), borderColor: 'rgba(75,192,192,1)',  backgroundColor: 'rgba(75,192,192,1)',  borderWidth: 2, pointRadius: 3, showLine: true },
          { label: 'Geogrid',        data: make(rows.map((r) => r.ltdsGeogrid)),  borderColor: 'rgba(255,99,132,1)',  backgroundColor: 'rgba(255,99,132,1)',  borderWidth: 2, pointRadius: 3, showLine: true },
          { label: 'Metallic Grid',  data: make(rows.map((r) => r.ltdsSg)),       borderColor: 'rgba(54,162,235,1)',  backgroundColor: 'rgba(54,162,235,1)',  borderWidth: 2, pointRadius: 3, showLine: true },
          { label: 'Metallic Strip', data: make(rows.map((r) => r.ltdsSs)),       borderColor: 'rgba(153,102,255,1)', backgroundColor: 'rgba(153,102,255,1)', borderWidth: 2, pointRadius: 3, showLine: true },
        ],
      },
      options: {
        responsive: false, parsing: false, animation: false,
        scales: {
          x: { type: 'linear', position: 'bottom', title: { display: true, text: 'Required Factored LTDS (kip/ft)' }, beginAtZero: true },
          y: { type: 'linear', title: { display: true, text: 'Depth below finished grade, z (ft)' }, beginAtZero: true, max: Math.ceil(maxZ + 1), reverse: true },
        },
        plugins: { legend: { position: 'top' } },
      },
    };
    const res = await fetch('https://quickchart.io/chart', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chart: chartConfig, width: 900, height: 600, backgroundColor: 'white' }),
    });
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  }
}

// ─── Word helpers ──────────────────────────────────────────────────────────────

const border = {
  top: { style: BorderStyle.SINGLE, size: 1 },
  bottom: { style: BorderStyle.SINGLE, size: 1 },
  left: { style: BorderStyle.SINGLE, size: 1 },
  right: { style: BorderStyle.SINGLE, size: 1 },
};

function wCell(text: string, header = false): TableCell {
  return new TableCell({
    borders: border,
    children: [new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text, bold: header, size: header ? 18 : 16 })],
    })],
  });
}

function wHRow(cols: string[]): TableRow { return new TableRow({ children: cols.map((c) => wCell(c, true)), tableHeader: true }); }
function wDRow(cols: string[]): TableRow { return new TableRow({ children: cols.map((c) => wCell(c)) }); }

function wTable(headers: string[], rows: string[][]): Table {
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [wHRow(headers), ...rows.map(wDRow)] });
}

function wSection(title: string): Paragraph {
  return new Paragraph({ text: title, heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 100 } });
}

function wTitle(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER });
}

function wLine(text: string, opts: { italic?: boolean; color?: string; size?: number } = {}): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
    children: [new TextRun({ text, italics: opts.italic, size: opts.size ?? 20, color: opts.color ?? '000000' })],
  });
}

function externalDocxChildren(sectionTitle: string, rows: AnalysisRow[], params: Record<string, string>) {
  return [
    wSection(sectionTitle),
    wSection('Input Parameters'),
    wTable(['Parameter', 'Value'], Object.entries(params)),
    wSection('Summary of Loads'),
    wTable(
      ['DH (ft)', 'RL (ft)', 'h_eq', 'P_LS.V', 'P_EV', 'M_LS.V', 'M_EV', 'P_LS.H', 'P_EH', 'P_EQ', 'M_LS.H', 'M_EH', 'M_EQ'],
      rows.map((r) => [N(r.dh, 2), N(r.rl, 2), N(r.hEq, 2), N(r.pLsV), N(r.pEv), N(r.mLsV), N(r.mEv), N(r.pLsH), N(r.pEh), N(r.pEq), N(r.mLsH), N(r.mEh), N(r.mEq)]),
    ),
    wSection('Load Combinations'),
    wTable(
      ['DH', 'Pu Ser-I V', 'Mu Ser-I V', 'Pu Str-I V', 'Mu Str-I V', 'Pu EE-I V', 'Mu EE-I V', 'Pu Ser-I L', 'Mu Ser-I L', 'Pu Str-I L', 'Mu Str-I L', 'Pu EE-I L', 'Mu EE-I L'],
      rows.map((r) => [N(r.dh, 2), N(r.puSerIV), N(r.muSerIV), N(r.puStrIV), N(r.muStrIV), N(r.puEeIV), N(r.muEeIV), N(r.puSerILat), N(r.muSerILat), N(r.puStrILat), N(r.muStrILat), N(r.puEeILat), N(r.muEeILat)]),
    ),
    wSection('Design Check — Strength I'),
    wTable(
      ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
      rows.map((r) => [N(r.dh, 2), N(r.eccBrgStrI), N(r.suBrgStrI), r.checkBrgStrI, N(r.eccOvtStrI), r.checkOvtStrI, N(r.phiRrStrIClass1), N(r.phiRrStrIFSoil), r.checkSldStrIClass1, r.checkSldStrIFSoil]),
    ),
    wSection('Design Check — Extreme Event I'),
    wTable(
      ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
      rows.map((r) => [N(r.dh, 2), N(r.eccBrgEeI), N(r.suBrgEeI), r.checkBrgEeI, N(r.eccOvtEeI), r.checkOvtEeI, N(r.phiRrEeIClass1), N(r.phiRrEeIFSoil), r.checkSldEeIClass1, r.checkSldEeIFSoil]),
    ),
    wSection('Design Check — Service I'),
    wTable(['DH', 'ecc Brg', 'Su Brg', 'Brg'], rows.map((r) => [N(r.dh, 2), N(r.eccBrgSerI), N(r.suBrgSerI), r.checkBrgSerI])),
    wSection('Percentage Demand (%)'),
    wTable(
      ['DH', 'Brg Str-I', 'Brg EE-I', 'Brg Ser-I', 'Ovt Str-I', 'Ovt EE-I', 'Sld Str-I', 'Sld EE-I', 'Ctrl %', 'Controls'],
      rows.map((r) => [N(r.dh, 2), N(r.demBrgStrI, 1), N(r.demBrgEeI, 1), N(r.demBrgSerI, 1), N(r.demOvtStrI, 1), N(r.demOvtEeI, 1), N(r.demSldStrI, 1), N(r.demSldEeI, 1), N(r.demCtrl, 1), r.limitState]),
    ),
    wSection('Demand Summary'),
    wTable(
      ['DH (ft)', 'RL (ft)', 'NL', 'Ctrl % Demand', 'Controlling Limit State'],
      rows.map((r) => [N(r.dh, 2), N(r.rl, 2), String(r.nl), N(r.demCtrl, 1), r.limitState]),
    ),
  ];
}

async function internalDocxChildren(sectionTitle: string, rows: InternalStabilityRow[], params: Record<string, string>) {
  const chartPng = await renderLtdsChart(rows);
  return [
    wSection(sectionTitle),
    wSection('Input Parameters'),
    wTable(['Parameter', 'Value'], Object.entries(params)),
    wSection('Stress / Load at Reinforcement Level'),
    wTable(
      ['DH (ft)', 'RL (ft)', 'z (ft)', 'σEV.Z', 'h_eq', 'σLS.Z', 'ωIR', 'ωAE', 'ωEQ.1', 'ωEQ.2', 'PEQ', 'σEQ'],
      rows.map((r) => [N(r.dh, 2), N(r.rl, 2), N(r.z, 2), N(r.sEvZ), N(r.hEq, 1), N(r.sLsZ), N(r.wIr, 3), N(r.wAe, 3), N(r.wEq1, 3), N(r.wEq2, 3), N(r.pEq, 3), N(r.sEq, 3)]),
    ),
    wSection('Geosynthetic Strip'),
    wTable(
      ['z (ft)', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
      rows.map((r) => [N(r.z, 2), N(r.sVStrI), N(r.sHStrI), N(r.sVEeI), N(r.sHEeI), N(r.tMaxStrIGstrip), N(r.tMaxEeIGstrip), N(r.lEStrIGs, 3), N(r.lEEeIGs, 3), N(r.lEGeostrip, 3), N(r.lAGs, 3), N(r.rlMinGeostrip, 3), N(r.ltdsGeostrip, 0), r.poGeostripCheck]),
    ),
    wSection('Geosynthetic Grid'),
    wTable(
      ['z (ft)', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
      rows.map((r) => [N(r.z, 2), N(r.sVStrI), N(r.sHStrI), N(r.sVEeI), N(r.sHEeI), N(r.tMaxStrIGgrid), N(r.tMaxEeIGgrid), N(r.lEStrIGg, 3), N(r.lEEeIGg, 3), N(r.lEGeogrid, 3), N(r.lAGg, 3), N(r.rlMinGeogrid, 3), N(r.ltdsGeogrid, 0), r.poGeogridCheck]),
    ),
    wSection('Metallic Grid'),
    wTable(
      ['z (ft)', "F'", 'kR.Sg', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
      rows.map((r) => [N(r.z, 2), N(r.fpMg), N(r.krSg), N(r.sVStrIMg), N(r.sHStrIMg), N(r.sVEeIMg), N(r.sHEeIMg), N(r.tMaxStrISg), N(r.tMaxEeISg), N(r.lEStrIMg, 3), N(r.lEEeIMg, 3), N(r.lESg, 3), N(r.lASg, 2), N(r.rlMinSg, 3), N(r.ltdsSg, 0), r.poSgCheck]),
    ),
    wSection('Ribbed Metallic Strip'),
    wTable(
      ['z (ft)', "F'", 'kR.Ss', 'σV Str-I', 'σH Str-I', 'σV EE-I', 'σH EE-I', 'Tmax Str-I', 'Tmax EE-I', 'lE Str-I', 'lE EE-I', 'lE', 'lA', 'RL min', 'LTDS (lb/ft)', 'PO Check'],
      rows.map((r) => [N(r.z, 2), N(r.fpSs), N(r.krSs), N(r.sVStrISs), N(r.sHStrISs), N(r.sVEeISs), N(r.sHEeISs), N(r.tMaxStrISs), N(r.tMaxEeISs), N(r.lEStrISs, 3), N(r.lEEeISs, 3), N(r.lESs, 3), N(r.lASs, 2), N(r.rlMinSs, 3), N(r.ltdsSs, 0), r.poSsCheck]),
    ),
    wSection('Required Factored LTDS (lb/ft)'),
    wTable(
      ['z (ft)', 'Geostrip Str-I', 'Geogrid Str-I', 'Met Grid Str-I', 'Rib Strip Str-I', 'Geostrip EE-I', 'Geogrid EE-I', 'Met Grid EE-I', 'Rib Strip EE-I'],
      rows.map((r) => [N(r.z, 2), N(r.ltdsGeostrip, 0), N(r.ltdsGeogrid, 0), N(r.ltdsSg, 0), N(r.ltdsSs, 0), N(r.ltdsEeIGs, 0), N(r.ltdsEeIGg, 0), N(r.ltdsEeISg, 0), N(r.ltdsEeISs, 0)]),
    ),
    wSection('Internal Stability — LTDS Chart'),
    ...(chartPng
      ? [new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 120, after: 120 },
          children: [new ImageRun({ type: 'png', data: chartPng, transformation: { width: 620, height: 413 } })],
        })]
      : [new Paragraph({ children: [new TextRun({ text: '(Chart not available in this environment)', italics: true, color: '999999' })] })]),
  ];
}

function titleBlock(d: { projectName: string; projectLocation: string; designTypeName: string; createdBy: string; generatedAt: Date }) {
  return [
    wTitle('MSE Design Analysis Report'),
    wLine(`${d.projectName} — ${d.projectLocation}`, { size: 22 }),
    wLine(d.designTypeName, { size: 20, italic: true }),
    wLine(`Generated by ${d.createdBy} on ${d.generatedAt.toLocaleDateString()}`, { size: 18, color: '666666' }),
  ];
}

// ─── Abutment combined ─────────────────────────────────────────────────────────

export async function generateCombinedAbutmentXlsx(d: AbutmentCombinedData): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = d.createdBy;
  wb.created = d.generatedAt;
  addInfoSheet(wb, 'Info', d, { ...d.extParams, ...d.intParams });
  addExternalSheets(wb, 'Ext-', d.extRows);
  await addInternalSheets(wb, 'Int-', d.intRows);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function generateCombinedAbutmentDocx(d: AbutmentCombinedData): Promise<Buffer> {
  const extChildren = externalDocxChildren('External Stability', d.extRows, d.extParams);
  const intChildren = await internalDocxChildren('Internal Stability', d.intRows, d.intParams);
  const doc = new Document({
    sections: [{ children: [...titleBlock(d), ...extChildren, ...intChildren] }],
  });
  return Packer.toBuffer(doc);
}

// ─── Wing combined ─────────────────────────────────────────────────────────────

export async function generateCombinedWingXlsx(d: WingCombinedData): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = d.createdBy;
  wb.created = d.generatedAt;
  addInfoSheet(wb, 'Info', d, { ...d.extParams, ...d.intParams });
  addExternalSheets(wb, 'ExtLL-', d.extLlRows);
  addExternalSheets(wb, 'ExtNL-', d.extNoLlRows);
  await addInternalSheets(wb, 'Int-', d.intRows);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function generateCombinedWingDocx(d: WingCombinedData): Promise<Buffer> {
  const extLlChildren = externalDocxChildren('External Stability (with LL)', d.extLlRows, d.extParams);
  const extNoLlChildren = externalDocxChildren('External Stability (without LL)', d.extNoLlRows, d.extParams);
  const intChildren = await internalDocxChildren('Internal Stability', d.intRows, d.intParams);
  const doc = new Document({
    sections: [{ children: [...titleBlock(d), ...extLlChildren, ...extNoLlChildren, ...intChildren] }],
  });
  return Packer.toBuffer(doc);
}

// ─── Panel face ────────────────────────────────────────────────────────────────

export async function generatePanelFaceXlsx(d: PanelFaceReportData): Promise<Buffer> {
  const { result: r, inputs: inp } = d;
  const MMin_pos_raw = Math.min(1.33 * r.MU_pos, 1.6 * 0.67 * r.Mcr);
  const MMin_neg_raw = Math.min(1.33 * r.MU_neg, 1.6 * 0.67 * r.Mcr);

  const wb = new ExcelJS.Workbook();
  wb.creator = d.createdBy;
  wb.created = d.generatedAt;
  addInfoSheet(wb, 'Info', d, d.params);

  addSheet(wb, 'Factored Load',
    ['HU.Str.Panel', 'HU.EE.Panel', 'HU.Panel (kip/ft)', 'MU.+ve (kip·ft)', 'MU.-ve (kip·ft)', 'VU.Panel (kip)'],
    [[inp.huStr, inp.huEe, r.HU_panel, r.MU_pos, r.MU_neg, r.VU_panel]],
  );
  addSheet(wb, 'Cracking Moment',
    ['fRupture (ksi)', 'SPanel (in³)', 'MCR (kip·ft)'],
    [[r.fr, r.St, r.Mcr]],
  );
  addSheet(wb, 'Min Moments',
    ['MMin.Pos (kip·ft)', 'MMin.Neg (kip·ft)', 'MU.+ve governing', 'MU.-ve governing', 'VU.Panel (kip)'],
    [[MMin_pos_raw, MMin_neg_raw, r.MMin_pos, r.MMin_neg, r.VU_panel]],
  );
  addSheet(wb, 'Flexural Capacity',
    ['Direction', 'β1', 'α1', 'c (in)', 'a (in)', 'εt', 'φf', 'MN', 'φMN', 'MU', 'φMN/MU', 'Reinforcement', 'Check'],
    [
      ['Hor +ve', r.beta1, r.alpha1, r.C_HorPos, r.a_HorPos, r.et_HorPos, r.phi_f_HorPos, r.MN_pos_Hor, r.phiMN_pos_Hor, r.MMin_pos, r.phiMN_pos_Hor / r.MMin_pos, `#${inp.barNumHor}@${inp.spacingHor}in`, r.check_HorPos_flex],
      ['Vert +ve', r.beta1, r.alpha1, r.C_VertPos, r.a_VertPos, r.et_VertPos, r.phi_f_VertPos, r.MN_pos_Vert, r.phiMN_pos_Vert, r.MMin_pos, r.phiMN_pos_Vert / r.MMin_pos, `#${inp.barNumVert}@${inp.spacingVert}in`, r.check_VertPos_flex],
      ['Hor -ve', r.beta1, r.alpha1, r.C_HorNeg, r.a_HorNeg, r.et_HorNeg, r.phi_f_HorNeg, r.MN_neg_Hor, r.phiMN_neg_Hor, r.MMin_neg, r.phiMN_neg_Hor / r.MMin_neg, `#${inp.barNumHor}@${inp.spacingHor}in`, r.check_HorNeg_flex],
      ['Vert -ve', r.beta1, r.alpha1, r.C_VertNeg, r.a_VertNeg, r.et_VertNeg, r.phi_f_VertNeg, r.MN_neg_Vert, r.phiMN_neg_Vert, r.MMin_neg, r.phiMN_neg_Vert / r.MMin_neg, `#${inp.barNumVert}@${inp.spacingVert}in`, r.check_VertNeg_flex],
    ],
  );
  addSheet(wb, 'Crack Control',
    ['Direction', 'SB (in)', 'γEV.Str.I', 'a (in)', 'γe', 'fSS (ksi)', 'dC (in)', 'βS', 'sMax.Crack (in)', 'Check'],
    [
      ['Horizontal', inp.spacingHor, 1.35, r.a_HorPos, 1.0, r.fs_Hor, r.dc_Hor, r.Vs_Hor, r.Smax_Hor, r.check_crack_Hor],
      ['Vertical',   inp.spacingVert, 1.35, r.a_VertPos, 1.0, r.fs_Vert, r.dc_Vert, r.Vs_Vert, r.Smax_Vert, r.check_crack_Vert],
    ],
  );
  addSheet(wb, 'Shear Capacity',
    ['VU.Panel (kip)', 'φV', 'β', 'VN.1 (kip)', 'VN.2 (kip)', 'VN.Panel (kip)', 'φVN.Panel (kip)', 'φVN/VU', 'Check'],
    [[r.VU_panel, 0.9, 2, r.Vc, r.Vc_max, Math.min(r.Vc, r.Vc_max), r.phiVc, r.phiVc / r.VU_panel, r.check_shear]],
  );

  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function generatePanelFaceDocx(d: PanelFaceReportData): Promise<Buffer> {
  const { result: r, inputs: inp } = d;
  const MMin_pos_raw = Math.min(1.33 * r.MU_pos, 1.6 * 0.67 * r.Mcr);
  const MMin_neg_raw = Math.min(1.33 * r.MU_neg, 1.6 * 0.67 * r.Mcr);

  const doc = new Document({
    sections: [{
      children: [
        ...titleBlock(d),
        wSection('Input Parameters'),
        wTable(['Parameter', 'Value'], Object.entries(d.params)),
        wSection('Factored Load on Panel'),
        wTable(
          ['HU.Str.Panel', 'HU.EE.Panel', 'HU.Panel (kip/ft)', 'MU.+ve (kip·ft)', 'MU.-ve (kip·ft)', 'VU.Panel (kip)'],
          [[N(inp.huStr), N(inp.huEe), N(r.HU_panel), N(r.MU_pos), N(r.MU_neg), N(r.VU_panel)]],
        ),
        wSection('Concrete Cracking Moment'),
        wTable(['fRupture (ksi)', 'SPanel (in³)', 'MCR (kip·ft)'], [[N(r.fr), N(r.St, 2), N(r.Mcr)]]),
        wSection('Minimum Applied Moment & Factored Ultimate Moment'),
        wTable(
          ['MMin.Pos (kip·ft)', 'MMin.Neg (kip·ft)', 'MU.+ve governing', 'MU.-ve governing', 'VU.Panel (kip)'],
          [[N(MMin_pos_raw), N(MMin_neg_raw), N(r.MMin_pos), N(r.MMin_neg), N(r.VU_panel)]],
        ),
        wSection('Flexural Capacity'),
        wTable(
          ['Direction', 'β1', 'α1', 'c (in)', 'a (in)', 'εt', 'φf', 'MN', 'φMN', 'MU', 'φMN/MU', 'Reinforcement', 'Check'],
          [
            ['Hor +ve', N(r.beta1), N(r.alpha1), N(r.C_HorPos), N(r.a_HorPos), N(r.et_HorPos, 5), N(r.phi_f_HorPos), N(r.MN_pos_Hor), N(r.phiMN_pos_Hor), N(r.MMin_pos), N(r.phiMN_pos_Hor / r.MMin_pos, 3), `#${inp.barNumHor}@${inp.spacingHor}in`, r.check_HorPos_flex],
            ['Vert +ve', N(r.beta1), N(r.alpha1), N(r.C_VertPos), N(r.a_VertPos), N(r.et_VertPos, 5), N(r.phi_f_VertPos), N(r.MN_pos_Vert), N(r.phiMN_pos_Vert), N(r.MMin_pos), N(r.phiMN_pos_Vert / r.MMin_pos, 3), `#${inp.barNumVert}@${inp.spacingVert}in`, r.check_VertPos_flex],
            ['Hor -ve', N(r.beta1), N(r.alpha1), N(r.C_HorNeg), N(r.a_HorNeg), N(r.et_HorNeg, 5), N(r.phi_f_HorNeg), N(r.MN_neg_Hor), N(r.phiMN_neg_Hor), N(r.MMin_neg), N(r.phiMN_neg_Hor / r.MMin_neg, 3), `#${inp.barNumHor}@${inp.spacingHor}in`, r.check_HorNeg_flex],
            ['Vert -ve', N(r.beta1), N(r.alpha1), N(r.C_VertNeg), N(r.a_VertNeg), N(r.et_VertNeg, 5), N(r.phi_f_VertNeg), N(r.MN_neg_Vert), N(r.phiMN_neg_Vert), N(r.MMin_neg), N(r.phiMN_neg_Vert / r.MMin_neg, 3), `#${inp.barNumVert}@${inp.spacingVert}in`, r.check_VertNeg_flex],
          ],
        ),
        wSection('Service I: Crack Control'),
        wTable(
          ['Direction', 'SB (in)', 'γEV.Str.I', 'a (in)', 'γe', 'fSS (ksi)', 'dC (in)', 'βS', 'sMax.Crack (in)', 'Check'],
          [
            ['Horizontal', N(inp.spacingHor, 3), '1.35', N(r.a_HorPos), '1.0', N(r.fs_Hor), N(r.dc_Hor), N(r.Vs_Hor), N(r.Smax_Hor), r.check_crack_Hor],
            ['Vertical',   N(inp.spacingVert, 3), '1.35', N(r.a_VertPos), '1.0', N(r.fs_Vert), N(r.dc_Vert), N(r.Vs_Vert), N(r.Smax_Vert), r.check_crack_Vert],
          ],
        ),
        wSection('Strength I: Shear Capacity'),
        wTable(
          ['VU.Panel (kip)', 'φV', 'β', 'VN.1 (kip)', 'VN.2 (kip)', 'VN.Panel (kip)', 'φVN.Panel (kip)', 'φVN/VU', 'Check'],
          [[N(r.VU_panel), '0.9', '2', N(r.Vc), N(r.Vc_max), N(Math.min(r.Vc, r.Vc_max)), N(r.phiVc), N(r.phiVc / r.VU_panel), r.check_shear]],
        ),
      ],
    }],
  });
  return Packer.toBuffer(doc);
}
