import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import ExcelJS from 'exceljs';
import type { AnalysisRow } from '@/lib/calculations/external-stability';

const N = (v: number, d = 4) => (isFinite(v) ? v.toFixed(d) : '—');

// ─── Shared data structure ─────────────────────────────────────────────────────

export interface ReportData {
  projectName: string;
  projectLocation: string;
  designTypeName: string;
  createdBy: string;
  generatedAt: Date;
  minRl: number;
  params: Record<string, string>;
  rows: AnalysisRow[];
}

// ─── Word (.docx) ─────────────────────────────────────────────────────────────

const border = {
  top: { style: BorderStyle.SINGLE, size: 1 },
  bottom: { style: BorderStyle.SINGLE, size: 1 },
  left: { style: BorderStyle.SINGLE, size: 1 },
  right: { style: BorderStyle.SINGLE, size: 1 },
};

function cell(text: string, header = false): TableCell {
  return new TableCell({
    borders: border,
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text, bold: header, size: header ? 18 : 16 })],
      }),
    ],
  });
}

function headerRow(cols: string[]): TableRow {
  return new TableRow({ children: cols.map((c) => cell(c, true)), tableHeader: true });
}

function dataRow(cols: string[]): TableRow {
  return new TableRow({ children: cols.map((c) => cell(c)) });
}

function section(title: string): Paragraph {
  return new Paragraph({
    text: title,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 80 },
  });
}

function makeTable(headers: string[], rows: string[][]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow(headers), ...rows.map(dataRow)],
  });
}

export async function generateDocx(d: ReportData): Promise<Buffer> {
  const { projectName, projectLocation, designTypeName, createdBy, generatedAt, params, rows } = d;

  const paramRows = Object.entries(params).map(([k, v]) => [k, v]);

  const doc = new Document({
    sections: [
      {
        children: [
          // Title block
          new Paragraph({
            text: 'MSE Design Analysis Report',
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: `${projectName} — ${projectLocation}`, size: 22 })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: designTypeName, size: 20, italics: true })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: `Generated by ${createdBy} on ${generatedAt.toLocaleDateString()}`,
                size: 18,
                color: '666666',
              }),
            ],
            spacing: { after: 240 },
          }),

          // Input parameters
          section('Input Parameters'),
          makeTable(['Parameter', 'Value'], paramRows),

          // Summary of Loads
          section('Summary of Loads'),
          makeTable(
            ['DH (ft)', 'RL (ft)', 'h_eq', 'P_LS.V', 'P_EV', 'M_LS.V', 'M_EV', 'P_LS.H', 'P_EH', 'P_EQ', 'M_LS.H', 'M_EH', 'M_EQ'],
            rows.map((r) => [
              N(r.dh, 2), N(r.rl, 2), N(r.hEq, 2),
              N(r.pLsV), N(r.pEv), N(r.mLsV), N(r.mEv),
              N(r.pLsH), N(r.pEh), N(r.pEq), N(r.mLsH), N(r.mEh), N(r.mEq),
            ]),
          ),

          // Load Combinations
          section('Load Combinations'),
          makeTable(
            ['DH', 'Pu Ser-I V', 'Mu Ser-I V', 'Pu Str-I V', 'Mu Str-I V', 'Pu EE-I V', 'Mu EE-I V', 'Pu Ser-I Lat', 'Mu Ser-I Lat', 'Pu Str-I Lat', 'Mu Str-I Lat', 'Pu EE-I Lat', 'Mu EE-I Lat'],
            rows.map((r) => [
              N(r.dh, 2),
              N(r.puSerIV), N(r.muSerIV), N(r.puStrIV), N(r.muStrIV),
              N(r.puEeIV), N(r.muEeIV),
              N(r.puSerILat), N(r.muSerILat), N(r.puStrILat), N(r.muStrILat),
              N(r.puEeILat), N(r.muEeILat),
            ]),
          ),

          // Design Check — Strength I
          section('Design Check — Strength I'),
          makeTable(
            ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
            rows.map((r) => [
              N(r.dh, 2), N(r.eccBrgStrI), N(r.suBrgStrI), r.checkBrgStrI,
              N(r.eccOvtStrI), r.checkOvtStrI,
              N(r.phiRrStrIClass1), N(r.phiRrStrIFSoil),
              r.checkSldStrIClass1, r.checkSldStrIFSoil,
            ]),
          ),

          // Design Check — Extreme Event I
          section('Design Check — Extreme Event I'),
          makeTable(
            ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
            rows.map((r) => [
              N(r.dh, 2), N(r.eccBrgEeI), N(r.suBrgEeI), r.checkBrgEeI,
              N(r.eccOvtEeI), r.checkOvtEeI,
              N(r.phiRrEeIClass1), N(r.phiRrEeIFSoil),
              r.checkSldEeIClass1, r.checkSldEeIFSoil,
            ]),
          ),

          // Design Check — Service I
          section('Design Check — Service I'),
          makeTable(
            ['DH', 'ecc Brg', 'Su Brg', 'Brg'],
            rows.map((r) => [N(r.dh, 2), N(r.eccBrgSerI), N(r.suBrgSerI), r.checkBrgSerI]),
          ),

          // Percentage Demand
          section('Percentage Demand (%)'),
          makeTable(
            ['DH', 'Brg Str-I', 'Brg EE-I', 'Brg Ser-I', 'Ovt Str-I', 'Ovt EE-I', 'Sld Str-I', 'Sld EE-I', 'Ctrl %', 'Controls'],
            rows.map((r) => [
              N(r.dh, 2),
              N(r.demBrgStrI, 1), N(r.demBrgEeI, 1), N(r.demBrgSerI, 1),
              N(r.demOvtStrI, 1), N(r.demOvtEeI, 1),
              N(r.demSldStrI, 1), N(r.demSldEeI, 1),
              N(r.demCtrl, 1), r.limitState,
            ]),
          ),

          // Demand Summary
          section('Demand Summary'),
          makeTable(
            ['DH (ft)', 'RL (ft)', 'NL', 'Ctrl % Demand', 'Controlling Limit State'],
            rows.map((r) => [
              N(r.dh, 2), N(r.rl, 2), String(r.nl), N(r.demCtrl, 1), r.limitState,
            ]),
          ),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}

// ─── Excel (.xlsx) ─────────────────────────────────────────────────────────────

const ADEQUATE_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFD1FAE5' },
};
const INADEQUATE_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFEE2E2' },
};

function addSheet(
  wb: ExcelJS.Workbook,
  name: string,
  headers: string[],
  data: (string | number)[][],
) {
  const ws = wb.addWorksheet(name);

  ws.addRow(headers).eachCell((c) => {
    c.font = { bold: true, size: 10 };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
    c.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    c.alignment = { horizontal: 'center', wrapText: true };
    c.border = {
      top: { style: 'thin' }, bottom: { style: 'thin' },
      left: { style: 'thin' }, right: { style: 'thin' },
    };
  });

  for (const row of data) {
    const r = ws.addRow(row);
    r.eachCell((c) => {
      c.alignment = { horizontal: 'center' };
      c.border = {
        top: { style: 'thin' }, bottom: { style: 'thin' },
        left: { style: 'thin' }, right: { style: 'thin' },
      };
      if (typeof c.value === 'string') {
        if (c.value === 'Adequate') c.fill = ADEQUATE_FILL;
        else if (c.value === 'Inadequate') { c.fill = INADEQUATE_FILL; c.font = { color: { argb: 'FF991B1B' } }; }
      }
    });
  }

  ws.columns.forEach((col) => { col.width = Math.max(10, (col.header?.toString().length ?? 10) + 4); });
}

export async function generateXlsx(d: ReportData): Promise<Buffer> {
  const { projectName, projectLocation, designTypeName, createdBy, generatedAt, params, rows } = d;
  const wb = new ExcelJS.Workbook();
  wb.creator = createdBy;
  wb.created = generatedAt;

  // Info sheet
  const info = wb.addWorksheet('Info');
  info.addRow(['MSE Design Analysis Report']);
  info.getRow(1).font = { bold: true, size: 14 };
  info.addRow(['Project', projectName]);
  info.addRow(['Location', projectLocation]);
  info.addRow(['Design Type', designTypeName]);
  info.addRow(['Generated By', createdBy]);
  info.addRow(['Date', generatedAt.toLocaleDateString()]);
  info.addRow([]);
  info.addRow(['Parameter', 'Value']);
  info.getRow(8).font = { bold: true };
  for (const [k, v] of Object.entries(params)) info.addRow([k, v]);
  info.columns = [{ width: 28 }, { width: 30 }];

  // Summary of Loads
  addSheet(
    wb, 'Summary of Loads',
    ['DH (ft)', 'RL (ft)', 'h_eq', 'P_LS.V', 'P_EV', 'M_LS.V', 'M_EV', 'P_LS.H', 'P_EH', 'P_EQ', 'M_LS.H', 'M_EH', 'M_EQ'],
    rows.map((r) => [
      r.dh, r.rl, r.hEq,
      r.pLsV, r.pEv, r.mLsV, r.mEv,
      r.pLsH, r.pEh, r.pEq, r.mLsH, r.mEh, r.mEq,
    ]),
  );

  // Load Combinations
  addSheet(
    wb, 'Load Combinations',
    ['DH', 'Pu Ser-I V', 'Mu Ser-I V', 'Pu Str-I V', 'Mu Str-I V', 'Pu EE-I V', 'Mu EE-I V', 'Pu Ser-I Lat', 'Mu Ser-I Lat', 'Pu Str-I Lat', 'Mu Str-I Lat', 'Pu EE-I Lat', 'Mu EE-I Lat'],
    rows.map((r) => [
      r.dh,
      r.puSerIV, r.muSerIV, r.puStrIV, r.muStrIV,
      r.puEeIV, r.muEeIV,
      r.puSerILat, r.muSerILat, r.puStrILat, r.muStrILat,
      r.puEeILat, r.muEeILat,
    ]),
  );

  // Strength I
  addSheet(
    wb, 'Design Check - Str I',
    ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
    rows.map((r) => [
      r.dh, r.eccBrgStrI, r.suBrgStrI, r.checkBrgStrI,
      r.eccOvtStrI, r.checkOvtStrI,
      r.phiRrStrIClass1, r.phiRrStrIFSoil,
      r.checkSldStrIClass1, r.checkSldStrIFSoil,
    ]),
  );

  // Extreme Event I
  addSheet(
    wb, 'Design Check - EE I',
    ['DH', 'ecc Brg', 'Su Brg', 'Brg', 'ecc Ovt', 'Ovt', 'φRr Class 1', 'φRr F.Soil', 'Sld Class 1', 'Sld F.Soil'],
    rows.map((r) => [
      r.dh, r.eccBrgEeI, r.suBrgEeI, r.checkBrgEeI,
      r.eccOvtEeI, r.checkOvtEeI,
      r.phiRrEeIClass1, r.phiRrEeIFSoil,
      r.checkSldEeIClass1, r.checkSldEeIFSoil,
    ]),
  );

  // Service I
  addSheet(
    wb, 'Design Check - Ser I',
    ['DH', 'ecc Brg', 'Su Brg', 'Brg'],
    rows.map((r) => [r.dh, r.eccBrgSerI, r.suBrgSerI, r.checkBrgSerI]),
  );

  // Percentage Demand
  addSheet(
    wb, '% Demand',
    ['DH', 'Brg Str-I', 'Brg EE-I', 'Brg Ser-I', 'Ovt Str-I', 'Ovt EE-I', 'Sld Str-I', 'Sld EE-I', 'Ctrl %', 'Controls'],
    rows.map((r) => [
      r.dh,
      r.demBrgStrI, r.demBrgEeI, r.demBrgSerI,
      r.demOvtStrI, r.demOvtEeI,
      r.demSldStrI, r.demSldEeI,
      r.demCtrl, r.limitState,
    ]),
  );

  // Demand Summary
  addSheet(
    wb, 'Demand Summary',
    ['DH (ft)', 'RL (ft)', 'NL', 'Ctrl % Demand', 'Controlling Limit State'],
    rows.map((r) => [r.dh, r.rl, r.nl, r.demCtrl, r.limitState]),
  );

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
